export const categories = [
  {
    label: 'CCTV Systems',
    products: [
      { img: 'DS-2CD1083G2-LIU.jpg', name: 'DS-2CD1083G2-LIU', desc: 'Outdoor Camera' },
      { img: 'DS-2CD2T83G2-2LI.jpg', name: 'DS-2CD2T83G2-2LI', desc: 'Outdoor Camera' },
      { img: 'DS-2CD2T87G2H-LI.jpg', name: 'DS-2CD2T87G2H-LI', desc: 'Outdoor Camera' },
      { img: 'DS-2CD2683G2-LIZS2U.jpg', name: 'DS-2CD2683G2-LIZS2U', desc: 'Outdoor Camera' },
      { img: 'DS-2DE7A825IW.jpg', name: 'DS-2DE7A825IW', desc: 'Outdoor PTZ Camera' },
      { img: 'DS-2CD2183G2-LIS2U.jpg', name: 'DS-2CD2183G2-LIS2U', desc: 'Indoor Camera' },
      { img: 'DS-2CD2783G2-LIZS2U.jpg', name: 'DS-2CD2783G2-LIZS2U', desc: 'Indoor Camera' },
      { img: 'DS-2CD2387G2P-LSU-SL.jpg', name: 'DS-2CD2387G2P-LSU/SL', desc: 'Indoor Camera' },
      { img: 'DS-7616NXI-K2.jpg', name: 'DS-7616NXI-K2', desc: 'NVR System' },
      { img: 'DS-9632NI-M8.jpg', name: 'DS-9632NI-M8', desc: 'NVR System' },
      { img: 'DS-9664NI-M8.jpg', name: 'DS-9664NI-M8', desc: 'NVR System' },
      { img: 'DS-96128NI-I16.jpg', name: 'DS-96128NI-I16', desc: 'NVR System' },
      { img: 'DS-1200KI.jpg', name: 'DS-1200KI', desc: 'Keyboard Controller' },
    ],
  },
  {
    label: 'Access Control',
    products: [
      { img: 'DS-KH6320-WTE1.jpg', name: 'DS-KH6320-WTE1', desc: 'Indoor Station' },
      { img: 'DS-KD8003-IME1.jpg', name: 'DS-KD8003-IME1', desc: 'Door Station' },
      { img: 'DS-K1T605EF.jpg', name: 'DS-K1T605EF', desc: 'Face Recognition Terminal' },
      { img: 'DS-K1T342MFWX-E1.jpg', name: 'DS-K1T342MFWX-E1', desc: 'Access Control Terminal' },
      { img: 'MB2000_ZK.jpg', name: 'MB2000 ZK', desc: 'Biometric Attendance Terminal' },
      { img: 'Speed_Face_V5L.jpg', name: 'Speed Face V5L', desc: 'Face Recognition Access Terminal' },
    ],
  },
  {
    label: 'Queue Management',
    products: [
      { img: '41_Queue_Display_99.jpg', name: 'Queue Display 99', desc: 'LED Digital Counter Display' },
      { img: '42_Queue_Kiosk.jpg', name: 'Queue Kiosk', desc: 'Ticket Dispenser Kiosk' },
      { img: '43_Queue_Keypad.jpg', name: 'Queue Keypad', desc: 'Queue Management Control Panel' },
      { img: '44_Ticket_Dispenser.jpg', name: 'Ticket Dispenser', desc: 'Take-A-Number System' },
      { img: '45_PA_Amplifier.jpg', name: 'PA Amplifier', desc: 'Public Address System Amplifier' },
      { img: '46_Ceiling_Speaker.jpg', name: 'Ceiling Speaker', desc: 'Flush Mount PA Speaker' },
      { img: '47_Megaphone.jpg', name: 'Megaphone', desc: 'Handheld Loudspeaker' },
      { img: '48_Queue_Microphones.jpg', name: 'Queue Microphones', desc: 'Desktop Gooseneck Microphones' },
    ],
  },
  {
    label: 'Alarm & Detection',
    products: [
      { img: '49_EAS_Antenna.jpg', name: 'EAS Antenna', desc: 'Retail Security Gate System' },
      { img: '50_EAS_Tags.jpg', name: 'EAS Tags', desc: 'Anti-Theft Security Tags' },
      { img: '51_Tag_Detacher.jpg', name: 'Tag Detacher', desc: 'Handheld Security Tag Remover' },
      { img: '52_Alarm_Control_Panel.jpg', name: 'Alarm Control Panel', desc: 'Security System Main Unit' },
      { img: '53_Alarm_Siren.jpg', name: 'Alarm Siren', desc: 'Outdoor Security Siren with Strobe' },
      { img: '54_PIR_Motion_Sensor.jpg', name: 'PIR Motion Sensor', desc: 'Passive Infrared Detector' },
      { img: '55_Magnetic_Contacts.jpg', name: 'Magnetic Contacts', desc: 'Door/Window Security Sensors' },
      { img: '56_Smoke_Detector.jpg', name: 'Smoke Detector', desc: 'Fire Alarm Smoke Sensor' },
      { img: '57_Security_Keypad.jpg', name: 'Security Keypad', desc: 'Alarm System Keypad' },
      { img: '58_Metal_Detector_Gate.jpg', name: 'Metal Detector Gate', desc: 'Walk-Through Security Scanner' },
      { img: '59_Handheld_Metal_Detector.jpg', name: 'Handheld Metal Detector', desc: 'Portable Security Wand' },
      { img: '60_Glass_Break_Sensor.jpg', name: 'Glass Break Sensor', desc: 'Acoustic Glass Break Detector' },
      { img: '64_Fire_Alarm_Panel.jpg', name: 'Fire Alarm Panel', desc: 'Fire Safety Control System' },
      { img: '70_Alarm_Keypad.jpg', name: 'Alarm Keypad', desc: 'Security System Keypad' },
      { img: '71_Alarm_Control_Box.jpg', name: 'Alarm Control Box', desc: 'Main Control Unit with Adapter' },
      { img: '74_Outdoor_Siren.jpg', name: 'Outdoor Siren', desc: 'Weatherproof Alarm Siren' },
      { img: '75_PIR_Sensor.jpg', name: 'PIR Sensor', desc: 'Motion Detection Sensor' },
      { img: '76_Smoke_Detector_2.jpg', name: 'Smoke Detector 2', desc: 'Fire Detection Sensor' },
    ],
  },
  {
    label: 'PBX Systems',
    products: [
      { img: 'UCM6302.jpg', name: 'UCM6302', desc: 'IP PBX System' },
      { img: 'GRP2601P.jpg', name: 'GRP2601P', desc: 'Business IP Phone' },
    ],
  },
  {
    label: 'Physical Security',
    products: [
      { img: '58_Metal_Detector_Gate.jpg', name: 'Metal Detector Gate', desc: 'Walk-Through Security Scanner' },
      { img: '59_Handheld_Metal_Detector.jpg', name: 'Handheld Metal Detector', desc: 'Portable Security Wand' },
      { img: '49_EAS_Antenna.jpg', name: 'EAS Antenna', desc: 'Retail Security Gate System' },
      { img: '50_EAS_Tags.jpg', name: 'EAS Tags', desc: 'Anti-Theft Security Tags' },
      { img: '51_Tag_Detacher.jpg', name: 'Tag Detacher', desc: 'Security Tag Remover' },
      { img: 'ps_arm_barrier.jpg', name: 'Arm Barrier', desc: 'Automatic Vehicle Barrier Gate' },
      { img: 'ps_perimeter_lighting.jpg', name: 'Perimeter Lighting System', desc: 'Security Perimeter Lighting' },
      { img: 'ps_road_blocker.jpg', name: 'Road Blocker', desc: 'Heavy Duty Road Blocker' },
      { img: 'ps_sliding_gate.webp', name: 'Sliding Gate', desc: 'Automated Sliding Security Gate' },
      { img: 'ps_static_bollards.webp', name: 'Static Bollards', desc: 'Fixed Security Bollards' },
      { img: 'ps_turnstile.png', name: 'Turnstile', desc: 'Pedestrian Access Turnstile' },
    ],
  },
];
